# Generated by Django 4.0.1 on 2022-01-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_city_alter_category_slug_alter_news_slug_news_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
